# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x0btodoPackage\"\x06\n\x04Void\"\x18\n\x08TodoText\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"1\n\tTodoItems\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.todoPackage.TodoItem\"\x17\n\x07LogData\x12\x0c\n\x04text\x18\x01 \x01(\t2\xb3\x01\n\x04Todo\x12:\n\nCreateTodo\x12\x15.todoPackage.TodoText\x1a\x15.todoPackage.TodoItem\x12\x36\n\treadTodos\x12\x11.todoPackage.Void\x1a\x16.todoPackage.TodoItems\x12\x37\n\ngetLogData\x12\x11.todoPackage.Void\x1a\x14.todoPackage.LogData0\x01\x62\x06proto3')



_VOID = DESCRIPTOR.message_types_by_name['Void']
_TODOTEXT = DESCRIPTOR.message_types_by_name['TodoText']
_TODOITEM = DESCRIPTOR.message_types_by_name['TodoItem']
_TODOITEMS = DESCRIPTOR.message_types_by_name['TodoItems']
_LOGDATA = DESCRIPTOR.message_types_by_name['LogData']
Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todoPackage.Void)
  })
_sym_db.RegisterMessage(Void)

TodoText = _reflection.GeneratedProtocolMessageType('TodoText', (_message.Message,), {
  'DESCRIPTOR' : _TODOTEXT,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todoPackage.TodoText)
  })
_sym_db.RegisterMessage(TodoText)

TodoItem = _reflection.GeneratedProtocolMessageType('TodoItem', (_message.Message,), {
  'DESCRIPTOR' : _TODOITEM,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todoPackage.TodoItem)
  })
_sym_db.RegisterMessage(TodoItem)

TodoItems = _reflection.GeneratedProtocolMessageType('TodoItems', (_message.Message,), {
  'DESCRIPTOR' : _TODOITEMS,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todoPackage.TodoItems)
  })
_sym_db.RegisterMessage(TodoItems)

LogData = _reflection.GeneratedProtocolMessageType('LogData', (_message.Message,), {
  'DESCRIPTOR' : _LOGDATA,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todoPackage.LogData)
  })
_sym_db.RegisterMessage(LogData)

_TODO = DESCRIPTOR.services_by_name['Todo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=27
  _VOID._serialized_end=33
  _TODOTEXT._serialized_start=35
  _TODOTEXT._serialized_end=59
  _TODOITEM._serialized_start=61
  _TODOITEM._serialized_end=97
  _TODOITEMS._serialized_start=99
  _TODOITEMS._serialized_end=148
  _LOGDATA._serialized_start=150
  _LOGDATA._serialized_end=173
  _TODO._serialized_start=176
  _TODO._serialized_end=355
# @@protoc_insertion_point(module_scope)
